### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LewisTehMinerz** [Comprehensive-Minecraft-Archive-Network/Owner-Discussion-Temp-#1]
Will there be new people on the team, or just us? (I think we should get modders and coders on this.)

**Comment by williambl** [comment]
Yeah, we should get more people in it...

**Comment by LewisTehMinerz** [comment]
I'll check out some Minecraft forums and in the Off-Topic section I'll post about recruiting.

**Comment by LewisTehMinerz** [comment]
Also, what about mod forums like ComputerCraft.info?

**Comment by williambl** [comment]
Might be classed as spam/off topic :/

**Comment by LewisTehMinerz** [comment]
TBH, ComputerCraft has a general section with the most confusing description ever, pretty much saying off-topic

**Comment by williambl** [comment]
K then.

**Comment by LewisTehMinerz** [comment]
Oh, also, advertise in your forum post.
