### ISSUE TITLE
waffle.io is thoroughly broken

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/Owner-Discussion-Temp-#2]
Every issue appears twice, and if you try to move the duplicate card, it errors!
Gah!

What shall we do: Stop using it, or try & fix it?

**Comment by LewisTehMinerz** [comment]
Waffle.IO has been fixed. It was caused due to a repository rename from CMAN to CMAN-Python.

**Comment by williambl** [comment]
Thanks.
